name: APPLY

on:
  workflow_dispatch: {}

env:
  TF_CLOUD_ORGANIZATION: "compan"
  TF_API_TOKEN: "${{ secrets.TFE_TOKEN }}"
  TF_WORKSPACE: "compan-workspace"
  CONFIG_DIRECTORY: "./"

jobs:
  create_pr:
    runs-on: ubuntu-latest
    outputs:
      LATEST_RUN_ID: ${{ steps.get-run-id.outputs.LATEST_RUN_ID }}
    steps:
      - name: Get latest Terraform run ID
        id: get-run-id
        run: |
          # Set your Terraform Cloud organization and workspace
          ORG_NAME="compan"
          WORKSPACE_NAME="compan-workspace"
          
          # Fetch the workspace ID
          WORKSPACE_ID=$(curl -s \
            --header "Authorization: Bearer ${{ secrets.TFE_TOKEN }}" \
            https://app.terraform.io/api/v2/organizations/${ORG_NAME}/workspaces/${WORKSPACE_NAME} | jq -r '.data.id')
          
          echo "Workspace ID: $WORKSPACE_ID"
          
          if [ "$WORKSPACE_ID" == "null" ]; then
            echo "Failed to fetch Workspace ID"
            exit 1
          fi
          
          # Fetch the latest run ID for the workspace
          LATEST_RUN_ID=$(curl -s \
            --header "Authorization: Bearer ${{ secrets.TFE_TOKEN }}" \
            https://app.terraform.io/api/v2/workspaces/${WORKSPACE_ID}/runs | jq -r '.data[0].id')
          
          echo "Latest Run ID: $LATEST_RUN_ID"

          # Set the output variable
          echo "::set-output name=LATEST_RUN_ID::$
