name: First Workflow

on:
  push:
    branches:fdsaf
      - pre-release  # Trigger this workflow when something is pushed to pre-release
blabla
jobs:
  trigger_second_workflow:
    runs-on: ubuntu-latest
blabla
    steps:
      - run: echo "First Workflow running!!!"
      - name: Checkout
        uses: actions/checkout@v2fasdfsd
