name: Take RDS DB Snapshot

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  take-snapshot:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::342023131128:role/github_role
          aws-region: us-east-1

      - name: Take RDS DB Snapshot
        run: |
          aws rds create-db-snapshot --db-instance-identifier nexus-intg --db-snapshot-identifier nexus-intg-snapshot
          
      - name: Wait for Snapshot to Complete
        run: |
            while true; do
              status=$(aws rds describe-db-snapshots --db-snapshot-identifier nexus-intg-snapshot --query 'DBSnapshots[0].Status' --output text)
              if [ "$status" = "available" ]; then
                echo "Snapshot completed successfully."
                break
              else
                echo "Snapshot is still in progress. Waiting..."
                sleep 30  # Adjust the sleep time as needed
              fi
            done
