name: Nexus one workflow

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  ecs:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: "eu-central-1"

      - name: Remove current ECS tasks
        id: task-remove
        run: |
          cluster="my-cluster"
          service="hello-world-service"
          
          # List tasks and store task ARNs in an array
          task_arns=$(aws ecs list-tasks --cluster $cluster --service-name $service --query "taskArns[]" --output text)
          
          if [ -z "$task_arns" ]; then
            echo "No tasks found for service $service in cluster $cluster."
          else
            # Stop each task
            for task_arn in $task_arns; do
                echo "Stopping task $task_arn"
                aws ecs stop-task --cluster $cluster --task $task_arn
            done
            
      - name: Download task definition
        id: task-def
        run: |
          aws ecs describe-task-definition --task-definition hello_world --query taskDefinition > hello_world.json

      - name: Deploy Amazon ECS task definition
        id: deploy
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: hello_world.json
          service: hello-world-service
          cluster: my-cluster
          wait-for-service-stability: true
