name: Nexus one workflow

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  ecs:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: "eu-central-1"
      - name: Remove current ECS task
        id: task-remove
        run: |
          task_arns=$(aws ecs list-tasks --cluster my-cluster --service-name hello-world-service | jq -r '.taskArns[]')
          for task_arn in $task_arns
          do
             aws ecs stop-task --cluster my-cluster --task $task_arn
          done

      - name: Download task definition
        id: task-def
        run: |
          aws ecs describe-task-definition --task-definition hello_world --query taskDefinition > hello_world.json

      - name: Deploy Amazon ECS task definition
        id: deploy
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: hello_world.json
          service: hello-world-service
          cluster: my-cluster
          wait-for-service-stability: true
