name: Create PR from pre-release to main

on:
  workflow_dispatch: {}
  workflow_run:
    workflows: ["Take RDS DB Snapshot"]
    types:
      - completed

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout pre-release branch
        uses: actions/checkout@v3
        with:
          ref: pre-release

      - name: Fetch main branch
        run: git fetch origin main

      - name: Check for differences
        run: |
          if git diff --exit-code origin/main; then
            echo "No changes detected"
            exit 0
          else
            echo "Changes detected"
          fi

      - name: Create pull request
        run: |
          pr_url=$(gh pr create -B main -H pre-release --title 'Merge pre-release into main' --body 'Created by GitHub action' --json url -q ".url")
          echo "Pull request created: $pr_url"
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Enable auto-merge on pull request
        run: |
          pr_number=$(gh pr list --base main --head pre-release --state open --json number --jq '.[0].number')
          gh pr merge $pr_number --auto --subject 'Merge pre-release into main' --body 'Auto-merged by GitHub Action'
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
