name: Workflow_02

on:
    workflow_dispatch: {}  # Empty object for manual triggering
    workflow_run:
        workflows: ["First Workflow"]
        types:
          - completed
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: peter-evans/create-pull-request@v6  # Assuming Node.js 20 compatible
        with:
            token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
            commit-message: 'Automated changes from pre-release'
            branch: main
            base: pre-release
            title: 'Automated Pull Request from pre-release to main'
            body: 'This pull request is created automatically from pre-release to main.'
