name: Workflow_02

on:
    workflow_dispatch: {}  # Empty object for manual triggering
    workflow_run:
        workflows: ["First Workflow"]
        types:
          - completed
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3

      - uses: peter-evans/create-pull-request@v6  # Assuming Node.js 20 compatible
        with:
            # token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
            commit-message: 'Automated changes from pre-release'
            branch: pre-release
            base: main
            title: 'Automated Pull Request from pre-release to main'
            body: 'This pull request is created automatically from pre-release to main.'

  # (Optional) Conditional Merge (use with caution)
  # auto-merge:
  #   runs-on: ubuntu-latest
  #   needs: create-pr  # This job waits for the create-pr job
  #   if: success()  # Only run if the create-pr job succeeds
  #   steps:
  #     - uses: actions/checkout@v3

  #     - uses: tiangolo/merge-pull-request@v4  # Assuming Node.js 20 compatible (check for updates)
  #       with:
  #         token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  #         # Add conditions for auto-merge (e.g., specific labels, comments, checks)
  #         # Example (replace with your conditions): merge_condition: 'includes: needs-review'
